### ISSUE TITLE
Proactive warning about running local clone without installing local dependencies

### ISSUE THREAD

**Issue by hawkeyexl** [doc-detective/doc-detective#97]
While most people install Doc Detective globally then run the `npx` command, this doesn't work in clones of the repository. When the working directory contains a definition for an `npx` command, `npx` *always* attempts to use the local directory, ignoring global NPM installs and the `npx` cache.

We should have a pre-run warning that detects if dependencies have been installed, and if not, prompts the user to install them. This would greatly enhance the user experience by catching errors instead of letting them happen and leaving users frustrated and confused.

**Comment by mjang** [comment]
> this doesn't work in clones of the repository

Oh that's an important detail!
